Implemented the dao delete volunteer info method
AtriaCoop/townhallbackend pull request #10
Opened 2024-07-16 02:06 UTC by GagenvirGill

2024-07-17 00:06 UTC, RYeeAnn approved these changes

2024-07-17 02:52 UTC, ansel-rangers11 requested changes

2024-07-17 02:52 UTC, ansel-rangers11 commented on townhall/myapi/dao.py
> +            return volunteer
Dont need to return the volunteer object, in which case can be solidified to one line 
`Volunteer.objects.get(id=volunteer_id).delete()`

2024-07-18 03:44 UTC, ansel-rangers11 approved these changes

2024-07-18 03:45 UTC, ansel-rangers11 commented
It looks like there's conflicting issue with main branch, to rectify do git pull on main, then do `git merge main` on this branch, then push that merge commit

2024-07-18 19:09 UTC, merged