Created the service delete volunteer method and the associated test
AtriaCoop/townhallbackend pull request #13
Opened 2024-07-18 19:27 UTC by GagenvirGill

2024-07-19 00:52 UTC, RYeeAnn approved these changes

2024-07-19 20:32 UTC, ansel-rangers11 requested changes
Small changes suggested

2024-07-19 20:32 UTC, ansel-rangers11 commented on townhall/myapi/tests.py
> +        townhall_services.VolunteerServices.delete_volunteer(id=1)
before calloimg delete_volunteer, it would be good to call get_volunter and assert` is not None`

2024-07-19 20:32 UTC, ansel-rangers11 commented on townhall/myapi/tests.py
> +        assert townhall_services.VolunteerServices.get_volunteer(id=1) == None
```suggestion
        assert townhall_services.VolunteerServices.get_volunteer(id=1) is None
```

2024-07-22 03:03 UTC, ansel-rangers11 approved these changes

2024-07-22 20:23 UTC, merged