Created GET endpoint to get single opportunity info by ID
AtriaCoop/townhallbackend pull request #27
Opened 2024-07-31 21:40 UTC by RYeeAnn

- Added serializers.py to convert Opportunity model instances to JSON and back.
- Added print statement in services.py for get_opportunity for debugging and testing purposes.
- Updated views.py to handle opportunity view (updated volunteer as well with @action)
- Updated urls.py to include opportunity view

I added an opportunity and volunteer under Django Admin. For testing purposes to getting an opportunity by a single ID, run python manage.py runserver. Then in Postman, you can GET http://127.0.0.1:8000/opportunity/?id=2 and it will show the opportunity data. You can also test volunteer with http://127.0.0.1:8000/volunteer/?id=1

2024-08-01 04:13 UTC, GagenvirGill approved these changes
Wow, Great work!

2024-08-03 22:00 UTC, ansel-rangers11 requested changes

2024-08-03 22:00 UTC, ansel-rangers11 commented on townhall/townhall/urls.py
> +    path('opportunity/', OpportunityViewSet.as_view({'get': 'get_opportunity'}))
Rename the` get_opportunity` here in corresponding to the rename above

2024-08-05 06:11 UTC, ansel-rangers11 approved these changes
Hmm I think I should have been clearer with my multi PR clarification, its all good, we can have a chat about it in our next 1:1, approved for now

2024-08-06 20:10 UTC, merged