Tow 44 Created GET endpoint to get ALL opportunities
AtriaCoop/townhallbackend pull request #31
Opened 2024-08-01 23:00 UTC by RYeeAnn

Similar to getting an opportunity by a single ID, this will fetch ALL opportunities. I added additional opportunities in Django Admin so we can fetch more than one opportunity for testing purposes.

- Run python manage.py runserver and in Postman, GET:  http://127.0.0.1:8000/opportunities/

2024-08-02 00:31 UTC, GagenvirGill approved these changes

2024-08-03 18:24 UTC, ansel-rangers11 requested changes
almost there, got a change to look at

2024-08-03 18:24 UTC, ansel-rangers11 commented on townhall/myapi/services.py
> +        opportunities = Opportunity.objects.all()
I think this should call the DAO method, service methods should never invoke DB operations like all() or get() or filter() etc

2024-08-03 18:24 UTC, ansel-rangers11 commented on townhall/myapi/services.py
> +        print(f"Fetched opportunity: {opportunity}")
Good logging

2024-08-03 18:24 UTC, ansel-rangers11 commented on townhall/myapi/views.py
> +from .services import OpportunityServices as opportunity_services
good whole file import, we prefer to do this than importing specific functions

2024-08-03 22:09 UTC, ansel-rangers11 commented
Try to merge this PR to` tow-43-get-opportunity-id` instead of `main` to result in cleaner commit history. See comment here https://github.com/AtriaCoop/townhallbackend/pull/32#discussion_r1702917482

2024-08-05 02:41 UTC, merged