Tow-64 and Tow-65
AtriaCoop/townhallbackend pull request #38
Opened 2024-08-13 21:29 UTC by RYeeAnn

Added Post and Comment model

2024-08-14 02:04 UTC, ansel-rangers11 requested changes

2024-08-14 02:04 UTC, ansel-rangers11 commented on townhall/myapi/models.py
> +    user = models.ForeignKey(User, on_delete=models.CASCADE)
Appropriate choice on the on_delete setting

2024-08-14 02:04 UTC, ansel-rangers11 commented on townhall/myapi/models.py
> +    comment_id = models.AutoField(primary_key=True)
for now just make all PK of every model `id`

2024-08-14 21:38 UTC, GagenvirGill approved these changes

2024-08-19 06:47 UTC, JordanBandur requested changes

2024-08-19 06:47 UTC, JordanBandur commented on townhall/myapi/models.py
> +        return self.id
The str method should return a string, self.id is an integer. 
consider converting it to a string: `return str(self.id)`

2024-08-19 06:47 UTC, JordanBandur commented on townhall/myapi/models.py
> +        return self.id
Same as above, consider converting self.id to a string

2024-08-21 00:09 UTC, JordanBandur approved these changes

2024-08-22 19:01 UTC, ansel-rangers11 approved these changes

2024-08-22 19:05 UTC, ansel-rangers11 requested changes
Usually a migration file is generated when making a new model, may need to run `makemigrations` https://docs.djangoproject.com/en/5.1/topics/migrations/

2024-08-23 01:31 UTC, ansel-rangers11 requested changes
I think you have to merge main first, then generate a migration since 0006 is already taken in main [0006_remove_organization_description_and_more.py](https://github.com/AtriaCoop/townhallbackend/blob/main/townhall/myapi/migrations/0006_remove_organization_description_and_more.py)

This is an example of a migration conflict, and its quite common to encounter unfortunately, the solution is to always check with main if someone else has merged in a new migration file, in which case, you will have to "regenerate" your migration such that the correct order is followed and there are no conflicting migration. Good learning opportunity here too @RYeeAnn @GagenvirGill @JordanBandur

2024-08-23 23:07 UTC, ansel-rangers11 approved these changes
Looks good, merge migration **should** work

2024-08-23 23:16 UTC, merged