TOW 40,41,93,94 - Organization endpoints for GET, PUT and DELETE
AtriaCoop/townhallbackend pull request #55
Opened 2024-08-29 03:34 UTC by RYeeAnn

## JIRA Ticket Link

## Migrations Required?
No

## Summary (a few sentences describing what this PR is doing) 
Created endpoints for getting organization by ID, getting ALL organizations, updating and deleting.

## Checks
Checked on postman (I created a shared account for Postman. Information will be on Notion soon.)

## Related PRs

## Impacted Areas in Application
List the areas in the app this PR is going to affect 
* dao, serializers, services, views, and urls.

## Learnings
Same for Volunteer and Organization endpoints

2024-08-30 02:01 UTC, ansel-rangers11 requested changes
Please add tests, specifically endpoint tests, think theres some examples in the test file how to do it

2024-09-09 21:42 UTC, RYeeAnn commented
NOTE : i fixed other endpoint tests so it accurately follows the naming convention in the ERD. when using pytest, everything should pass

2024-09-17 05:55 UTC, ansel-rangers11 approved these changes

2024-09-19 00:03 UTC, GagenvirGill approved these changes

2024-09-23 20:38 UTC, merged