Tow 172 update volunteer opportunity relation
AtriaCoop/townhallbackend pull request #60
Opened 2024-09-19 03:09 UTC by GagenvirGill

## JIRA Ticket Link
https://atriadev.atlassian.net/jira/software/projects/TOW/boards/1?atlOrigin=eyJpIjoiYzc2YzEwZGU3OTJmNDYyNjgzYWZmZDBhMWY2ZmEyMjkiLCJwIjoiSmlyYS1Ob3Rpb25EQnN5bi1JbnQifQ&selectedIssue=TOW-172

## Migrations Required?
YES

## Summary (a few sentences describing what this PR is doing) 
This PR fixes a typo error in the model regarding the volunteer opportunity relation. This PR also creates a few CRUD methods that were missing regarding this relation also.

## Checks
-  I have ran all the tests locally, and they all pass

## Impacted Areas in Application
List the areas in the app this PR is going to affect 
- Migrations Files 
- Opportunity DAO, Service and Models classes and the Opportunity Test file

## Learnings
This task reinforced my learning of refactoring code as well as a basic form of regression testing (Refactoring and making changes to code while ensuring that previous functionality remains the same).

2024-09-20 22:16 UTC, ansel-rangers11 requested changes

2024-09-20 22:16 UTC, ansel-rangers11 commented on townhall/myapi/dao.py
> +    def get_all_opportunities_volunteers(opportunity_id: int) -> QuerySet[Volunteer]:
The name is quite similar and can be mistaken for the other below method, I suggest `get_all_volunteers_of_an_opportunity`

2024-09-20 22:16 UTC, ansel-rangers11 commented on townhall/myapi/dao.py
> +    def get_all_volunteers_opportunities(volunteer_id: int) -> QuerySet[Opportunity]:
Same comment, I suggest `get_all_opportunitiies_of_a_volunteer`

2024-09-25 18:08 UTC, JordanBandur approved these changes

2024-09-26 04:06 UTC, ansel-rangers11 approved these changes

2024-09-27 18:38 UTC, merged