Tow 97 Create event model
AtriaCoop/townhallbackend pull request #73
Opened 2024-10-28 00:07 UTC by aldog27

## JIRA Ticket Link
https://atriadev.atlassian.net/browse/TOW-97?atlOrigin=eyJpIjoiODY4ZjM4NTEwNzJlNDQ2ZjhmZmViYWM5M2QwNDhlMDQiLCJwIjoiaiJ9

## Migrations Required?
YES :white_check_mark:

## Summary (a few sentences describing what this PR is doing) 
Created the Event model

## Checks
-  [ ] I have ran all the tests locally, and they all pass

## Related PRs

## Impacted Areas in Application
List the areas in the app this PR is going to affect 
DAO and service methods for Event

## Learnings
Describe in 1-2 sentences what you learned from doing this task
Learnt about migrations

2024-10-28 01:01 UTC, ansel-rangers11 requested changes

2024-10-28 01:01 UTC, ansel-rangers11 commented on townhall/myapi/migrations/0020_alter_volunteer_password_event_delete_message.py
> +        migrations.DeleteModel(
This shouldnt be here, i think Message is one of the newer models we are adding?

2024-10-28 01:01 UTC, ansel-rangers11 commented on townhall/myapi/migrations/0020_alter_volunteer_password_event_delete_message.py
> +        migrations.AlterField(
Not sure why this is here either

2024-11-02 22:11 UTC, ansel-rangers11 approved these changes

2024-11-03 01:23 UTC, GagenvirGill approved these changes

2024-11-03 21:21 UTC, merged